name: ${project.name}
version: ${project.version}
description: ${project.description}
main: com.github.hexosse.grounditemoundItemPlugin

author: hexosse
website: www.github.hexosse

softdepend: [Multiverse-Core, MultiWorld, WorldEdit, WorldGuard]
